port: "8000"

postgres:
  username: "postgres"
  host: "postgres_db"
  port: "5432"
  dbname: "todoapp"
  sslmode: disable

redis:
  host: "redis_db"
  username: "todoapp"
  dbname: 0
  retries: 5
  dialtimout: 10
  timeout: 5
  

